"""
=============================================================================
AUTO-RICKSHAW PROFIT MAXIMIZER - ML MODEL TRAINING
=============================================================================
This script trains a Random Forest model to predict passenger demand
across different zones in Chennai.

We train TWO models:
1. Random Forest CLASSIFIER - predicts demand level (High/Medium/Low)
2. Random Forest REGRESSOR  - predicts demand score (0-100) for heatmap

Algorithm Choice: Random Forest
- Works well with mixed feature types (numerical + categorical)
- Handles non-linear relationships
- Resistant to overfitting
- Provides feature importance scores (useful for understanding the model)
- Fast inference (important for real-time predictions)

Author: Auto-Driver Profit Maximizer Project
Date: 2026
=============================================================================
"""

import os
import pickle
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score, 
    classification_report, 
    confusion_matrix,
    mean_absolute_error,
    r2_score
)


def load_and_prepare_data():
    """
    Load the generated demand data and prepare features for training.
    
    Feature Engineering:
    - is_peak_hour: Binary flag for rush hours (8-10 AM, 5-7 PM)
    - is_morning: Binary flag for morning hours (6-11 AM)
    - is_evening: Binary flag for evening hours (4-9 PM)
    - is_night: Binary flag for night hours (10 PM - 5 AM)
    
    Returns:
        X: Feature matrix
        y_class: Classification target (High/Medium/Low)
        y_reg: Regression target (demand score 0-100)
        feature_names: List of feature names
    """
    print("\n" + "=" * 60)
    print("  LOADING & PREPARING DATA")
    print("=" * 60)
    
    # Load the dataset generated by scraper.py
    data_path = os.path.join("data", "ride_demand_data.csv")
    df = pd.read_csv(data_path)
    print(f"\n  [OK] Loaded {len(df)} samples from {data_path}")
    print(f"  [OK] Columns: {list(df.columns)}")
    
    # ---------- FEATURE ENGINEERING ----------
    # Create additional features that capture time patterns
    
    # Peak hours: when most people commute (8-10 AM, 5-7 PM)
    df["is_peak_hour"] = ((df["hour"].between(8, 10)) | 
                          (df["hour"].between(17, 19))).astype(int)
    
    # Time of day categories
    df["is_morning"] = df["hour"].between(6, 11).astype(int)
    df["is_evening"] = df["hour"].between(16, 21).astype(int)
    df["is_night"] = ((df["hour"] >= 22) | (df["hour"] <= 5)).astype(int)
    
    # Hour cyclical encoding (helps ML model understand that hour 23 is close to 0)
    df["hour_sin"] = np.sin(2 * np.pi * df["hour"] / 24)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour"] / 24)
    
    # Day cyclical encoding
    df["day_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7)
    df["day_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7)
    
    # ---------- SELECT FEATURES ----------
    feature_names = [
        "hour", "day_of_week", "is_weekend", "weather", "temperature",
        "nearby_pois_count", "has_hospital", "has_bus_stop",
        "has_railway_station", "has_market", "has_school",
        "is_peak_hour", "is_morning", "is_evening", "is_night",
        "hour_sin", "hour_cos", "day_sin", "day_cos"
    ]
    
    X = df[feature_names]
    y_class = df["demand_level"]      # For classification
    y_reg = df["demand_score"]        # For regression
    
    print(f"\n  Features ({len(feature_names)}):")
    for i, name in enumerate(feature_names, 1):
        print(f"    {i:2d}. {name}")
    
    print(f"\n  Target distribution (Classification):")
    print(f"    {y_class.value_counts().to_string()}")
    
    print(f"\n  Target statistics (Regression):")
    print(f"    Mean:   {y_reg.mean():.1f}")
    print(f"    Median: {y_reg.median():.1f}")
    print(f"    Std:    {y_reg.std():.1f}")
    print(f"    Min:    {y_reg.min():.1f}")
    print(f"    Max:    {y_reg.max():.1f}")
    
    return X, y_class, y_reg, feature_names


def train_classifier(X_train, X_test, y_train, y_test, feature_names):
    """
    Train a Random Forest Classifier to predict demand LEVEL.
    
    The classifier predicts: High, Medium, or Low demand.
    This is used for color-coding zones on the map.
    
    Returns:
        model: Trained RandomForestClassifier
        label_encoder: LabelEncoder for decoding predictions
        accuracy: Test set accuracy
    """
    print("\n" + "=" * 60)
    print("  TRAINING: Random Forest CLASSIFIER")
    print("=" * 60)
    
    # Encode labels: High=0, Low=1, Medium=2 (alphabetical order)
    le = LabelEncoder()
    y_train_encoded = le.fit_transform(y_train)
    y_test_encoded = le.transform(y_test)
    
    print(f"\n  Label encoding: {dict(zip(le.classes_, le.transform(le.classes_)))}")
    
    # Create and train the Random Forest Classifier
    # n_estimators=100: Use 100 decision trees in the forest
    # max_depth=15: Limit tree depth to prevent overfitting
    # random_state=42: For reproducible results
    clf = RandomForestClassifier(
        n_estimators=100,      # Number of trees in the forest
        max_depth=15,          # Maximum depth of each tree
        min_samples_split=5,   # Minimum samples to split a node
        min_samples_leaf=2,    # Minimum samples in a leaf node
        random_state=42,       # Reproducibility seed
        n_jobs=-1              # Use all CPU cores for parallel training
    )
    
    print("\n  Training model with 100 trees...")
    clf.fit(X_train, y_train_encoded)
    
    # ---------- EVALUATE THE MODEL ----------
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test_encoded, y_pred)
    
    print(f"\n  [OK] Model trained successfully!")
    print(f"\n  === CLASSIFICATION RESULTS ===")
    print(f"  Accuracy: {accuracy * 100:.2f}%")
    
    print(f"\n  Classification Report:")
    report = classification_report(y_test_encoded, y_pred, 
                                   target_names=le.classes_)
    for line in report.split("\n"):
        print(f"    {line}")
    
    # Feature importances - which features matter most?
    importances = clf.feature_importances_
    importance_df = pd.DataFrame({
        "feature": feature_names,
        "importance": importances
    }).sort_values("importance", ascending=False)
    
    print(f"\n  Top 10 Feature Importances:")
    for i, (_, row) in enumerate(importance_df.head(10).iterrows(), 1):
        bar = "#" * int(row["importance"] * 50)
        print(f"    {i:2d}. {row['feature']:<25s} {row['importance']:.4f} {bar}")
    
    return clf, le, accuracy, importance_df


def train_regressor(X_train, X_test, y_train, y_test, feature_names):
    """
    Train a Random Forest Regressor to predict demand SCORE.
    
    The regressor predicts a continuous score (0-100).
    This is used for sizing zone markers on the heatmap.
    
    Returns:
        model: Trained RandomForestRegressor
        mae: Mean Absolute Error on test set
        r2: R-squared score on test set
    """
    print("\n" + "=" * 60)
    print("  TRAINING: Random Forest REGRESSOR")
    print("=" * 60)
    
    # Create and train the regressor
    reg = RandomForestRegressor(
        n_estimators=100,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    )
    
    print("\n  Training regressor with 100 trees...")
    reg.fit(X_train, y_train)
    
    # Evaluate
    y_pred = reg.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    print(f"\n  [OK] Regressor trained successfully!")
    print(f"\n  === REGRESSION RESULTS ===")
    print(f"  Mean Absolute Error: {mae:.2f} (average prediction error in demand points)")
    print(f"  R² Score:           {r2:.4f} (1.0 = perfect, 0.0 = baseline)")
    
    return reg, mae, r2


def save_models(classifier, regressor, label_encoder, accuracy, mae, r2, importance_df):
    """
    Save trained models and metadata to disk using pickle.
    
    Files saved:
    - model/classifier.pkl: Random Forest Classifier
    - model/regressor.pkl: Random Forest Regressor
    - model/label_encoder.pkl: Label encoder for demand levels
    - model/model_info.pkl: Model performance metrics
    """
    print("\n" + "=" * 60)
    print("  SAVING MODELS")
    print("=" * 60)
    
    os.makedirs("model", exist_ok=True)
    
    # Save classifier
    with open(os.path.join("model", "classifier.pkl"), "wb") as f:
        pickle.dump(classifier, f)
    print("  [OK] Saved model/classifier.pkl")
    
    # Save regressor
    with open(os.path.join("model", "regressor.pkl"), "wb") as f:
        pickle.dump(regressor, f)
    print("  [OK] Saved model/regressor.pkl")
    
    # Save label encoder
    with open(os.path.join("model", "label_encoder.pkl"), "wb") as f:
        pickle.dump(label_encoder, f)
    print("  [OK] Saved model/label_encoder.pkl")
    
    # Save model performance info (used by the web app)
    model_info = {
        "classifier_accuracy": accuracy,
        "regressor_mae": mae,
        "regressor_r2": r2,
        "feature_importances": importance_df.to_dict("records"),
        "n_estimators": 100,
        "algorithm": "Random Forest",
    }
    with open(os.path.join("model", "model_info.pkl"), "wb") as f:
        pickle.dump(model_info, f)
    print("  [OK] Saved model/model_info.pkl")


def main():
    """Main training pipeline."""
    
    print("\n" + "=" * 60)
    print("  AUTO-RICKSHAW PROFIT MAXIMIZER")
    print("  ML Model Training Pipeline")
    print("=" * 60)
    
    # Step 1: Load and prepare data
    X, y_class, y_reg, feature_names = load_and_prepare_data()
    
    # Step 2: Split into training and test sets (80% train, 20% test)
    # We use the same split for both classifier and regressor
    X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = \
        train_test_split(X, y_class, y_reg, test_size=0.2, random_state=42)
    
    print(f"\n  Train/Test Split:")
    print(f"    Training samples: {len(X_train)}")
    print(f"    Test samples:     {len(X_test)}")
    
    # Step 3: Train the classifier
    classifier, label_encoder, accuracy, importance_df = train_classifier(
        X_train, X_test, y_class_train, y_class_test, feature_names
    )
    
    # Step 4: Train the regressor
    regressor, mae, r2 = train_regressor(
        X_train, X_test, y_reg_train, y_reg_test, feature_names
    )
    
    # Step 5: Save everything
    save_models(classifier, regressor, label_encoder, accuracy, mae, r2, importance_df)
    
    # Final summary
    print("\n" + "=" * 60)
    print("  TRAINING COMPLETE!")
    print("=" * 60)
    print(f"  Classifier Accuracy: {accuracy * 100:.2f}%")
    print(f"  Regressor MAE:       {mae:.2f}")
    print(f"  Regressor R²:        {r2:.4f}")
    print(f"\n  Next step: Run 'python app.py' to start the web application")
    print("=" * 60)


if __name__ == "__main__":
    main()
